### ISSUE TITLE
rectangular puzzles

### ISSUE THREAD

**Issue by M0untacir** [ahmed4end/Math-crossword-puzzle-generator#2]
Hi,
Is it possible to generate rectangular puzzles instead of square?

**Comment by ahmed4end** [comment]
Yes it can be done.

**Comment by M0untacir** [comment]
This is the easiest modification i thought of trying to make it generate rectangular puzzles, but no luck.
Only the shorter side fills if the target is small, if i increase it, the counter never reaches the target.
If you could help or point me to the right direction i'd appreciate it.
Thank you


def __init__(self):
    self.COLS = 15
    self.ROWS = 23
    self.dims = 0
    self.target = 20

arr = [[0 for i in range(self.ROWS)] for j in range(self.COLS)]

try:
    xy = choice(list(xhis)) if counter%2==0 else choice(list(yhis))
    self.dims = self.ROWS if counter%2==0 else self.COLS
except:
    continue

**Comment by ahmed4end** [comment]
Actually, I planned to rewrite this code to perform this task using a more efficient algorithm (backtracking), which will be more powerful and will fix the issue of never reaching the target. I will do it, maybe in one month time. if you good with the Arabic language you can join my telegram and wait for my post of the new algorithm to perform this puzzles.(https://t.me/math4end)
